[build]
command = "bun run build"
publish = "build/client"

[dev]
command = "bun run storybook"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"


[[headers]]
for = "/storybook-static/*"
[headers.values]
Cache-Control = "public, max-age=31560000, immutable"

[[redirects]]
from = "/storybook"
to = "/storybook-static"
status = 200
