[build]
command = """
    curl -fsSL https://bun.sh/install | bash
    export BUN_INSTALL="$HOME/.bun"
    export PATH="$BUN_INSTALL/bin:$PATH"
    echo "//npm.fontawesome.com/:_authToken=$FONTAWESOME_NPM_AUTH_TOKEN" >> .npmrc
    bun install
    bun run build
  """
publish = "public"

[build.environment]
NODE_VERSION = "20.15.0"
FONTAWESOME_NPM_AUTH_TOKEN = "66B42FD2-8877-4678-B62A-61A4F8470C93"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[install.scopes]
"@fortawesome" = { token = "${FONTAWESOME_NPM_AUTH_TOKEN}", url = "https://npm.fontawesome.com/" }
