[build]
command = "bun run build && bun run build-storybook"
publish = "build/client"

[dev]
command = "bun run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"
[headers.values]
Cache-Control = "public, max-age=31560000, immutable"

[[headers]]
for = "/build/client/storybook-static/*"
[headers.values]
Cache-Control = "public, max-age=31560000, immutable"

[[redirects]]
from = "/storybook"
to = "/build/client/storybook-static"
status = 200
