import typography from "@tailwindcss/typography";
import type { Config } from 'tailwindcss'
import {
  mauve, violet, blackA, whiteA, mauveDark, violetDark,
  blue, red, green, yellow, blueDark, redDark, greenDark, yellowDark
} from "@radix-ui/colors";

const config: Config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: {
          DEFAULT: `light-dark(${mauve.mauve1}, ${mauveDark.mauve1})`,
          hover: `light-dark(${mauve.mauve2}, ${mauveDark.mauve2})`,
          active: `light-dark(${mauve.mauve3}, ${mauveDark.mauve3})`,
          focus: `light-dark(${mauve.mauve4}, ${mauveDark.mauve4})`,
          disabled: `light-dark(${mauve.mauve2}, ${mauveDark.mauve2})`,
          loading: `light-dark(${mauve.mauve3}, ${mauveDark.mauve3})`,
        },
        foreground: {
          DEFAULT: `light-dark(${mauve.mauve12}, ${mauveDark.mauve12})`,
          hover: `light-dark(${mauve.mauve11}, ${mauveDark.mauve11})`,
          active: `light-dark(${mauve.mauve10}, ${mauveDark.mauve10})`,
          focus: `light-dark(${mauve.mauve12}, ${mauveDark.mauve12})`,
          disabled: `light-dark(${mauve.mauve8}, ${mauveDark.mauve8})`,
          loading: `light-dark(${mauve.mauve9}, ${mauveDark.mauve9})`,
        },
        muted: {
          DEFAULT: `light-dark(${mauve.mauve3}, ${mauveDark.mauve3})`,
          hover: `light-dark(${mauve.mauve4}, ${mauveDark.mauve4})`,
          active: `light-dark(${mauve.mauve5}, ${mauveDark.mauve5})`,
          focus: `light-dark(${mauve.mauve6}, ${mauveDark.mauve6})`,
          disabled: `light-dark(${mauve.mauve2}, ${mauveDark.mauve2})`,
          loading: `light-dark(${mauve.mauve3}, ${mauveDark.mauve3})`,
        },
        accent: {
          DEFAULT: `light-dark(${violet.violet9}, ${violetDark.violet9})`,
          hover: `light-dark(${violet.violet10}, ${violetDark.violet10})`,
          active: `light-dark(${violet.violet11}, ${violetDark.violet11})`,
          focus: `light-dark(${violet.violet8}, ${violetDark.violet8})`,
          disabled: `light-dark(${violet.violet6}, ${violetDark.violet6})`,
          loading: `light-dark(${violet.violet7}, ${violetDark.violet7})`,
        },
        border: {
          DEFAULT: `light-dark(${mauve.mauve6}, ${mauveDark.mauve6})`,
          hover: `light-dark(${mauve.mauve8}, ${mauveDark.mauve8})`,
          active: `light-dark(${mauve.mauve9}, ${mauveDark.mauve9})`,
          focus: `light-dark(${violet.violet8}, ${violetDark.violet8})`,
          disabled: `light-dark(${mauve.mauve5}, ${mauveDark.mauve5})`,
          loading: `light-dark(${mauve.mauve7}, ${mauveDark.mauve7})`,
        },
        ring: {
          DEFAULT: `light-dark(${violet.violet8}, ${violetDark.violet8})`,
          hover: `light-dark(${violet.violet9}, ${violetDark.violet9})`,
          active: `light-dark(${violet.violet10}, ${violetDark.violet10})`,
          focus: `light-dark(${violet.violet11}, ${violetDark.violet11})`,
          disabled: `light-dark(${violet.violet6}, ${violetDark.violet6})`,
          loading: `light-dark(${violet.violet7}, ${violetDark.violet7})`,
        },
        destructive: {
          background: {
            DEFAULT: `light-dark(${red.red3}, ${redDark.red3})`,
            hover: `light-dark(${red.red4}, ${redDark.red4})`,
            active: `light-dark(${red.red5}, ${redDark.red5})`,
            focus: `light-dark(${red.red6}, ${redDark.red6})`,
            disabled: `light-dark(${red.red2}, ${redDark.red2})`,
            loading: `light-dark(${red.red3}, ${redDark.red3})`,
          },
          foreground: {
            DEFAULT: `light-dark(${red.red11}, ${redDark.red11})`,
            hover: `light-dark(${red.red12}, ${redDark.red12})`,
            active: `light-dark(${red.red12}, ${redDark.red12})`,
            focus: `light-dark(${red.red12}, ${redDark.red12})`,
            disabled: `light-dark(${red.red8}, ${redDark.red8})`,
            loading: `light-dark(${red.red9}, ${redDark.red9})`,
          },
          border: {
            DEFAULT: `light-dark(${red.red7}, ${redDark.red7})`,
            hover: `light-dark(${red.red8}, ${redDark.red8})`,
            active: `light-dark(${red.red9}, ${redDark.red9})`,
            focus: `light-dark(${red.red10}, ${redDark.red10})`,
            disabled: `light-dark(${red.red5}, ${redDark.red5})`,
            loading: `light-dark(${red.red6}, ${redDark.red6})`,
          },
        },
        success: {
          background: {
            DEFAULT: `light-dark(${green.green3}, ${greenDark.green3})`,
            hover: `light-dark(${green.green4}, ${greenDark.green4})`,
            active: `light-dark(${green.green5}, ${greenDark.green5})`,
            focus: `light-dark(${green.green6}, ${greenDark.green6})`,
            disabled: `light-dark(${green.green2}, ${greenDark.green2})`,
            loading: `light-dark(${green.green3}, ${greenDark.green3})`,
          },
          foreground: {
            DEFAULT: `light-dark(${green.green11}, ${greenDark.green11})`,
            hover: `light-dark(${green.green12}, ${greenDark.green12})`,
            active: `light-dark(${green.green12}, ${greenDark.green12})`,
            focus: `light-dark(${green.green12}, ${greenDark.green12})`,
            disabled: `light-dark(${green.green8}, ${greenDark.green8})`,
            loading: `light-dark(${green.green9}, ${greenDark.green9})`,
          },
          border: {
            DEFAULT: `light-dark(${green.green7}, ${greenDark.green7})`,
            hover: `light-dark(${green.green8}, ${greenDark.green8})`,
            active: `light-dark(${green.green9}, ${greenDark.green9})`,
            focus: `light-dark(${green.green10}, ${greenDark.green10})`,
            disabled: `light-dark(${green.green5}, ${greenDark.green5})`,
            loading: `light-dark(${green.green6}, ${greenDark.green6})`,
          },
        },
        warning: {
          background: {
            DEFAULT: `light-dark(${yellow.yellow3}, ${yellowDark.yellow3})`,
            hover: `light-dark(${yellow.yellow4}, ${yellowDark.yellow4})`,
            active: `light-dark(${yellow.yellow5}, ${yellowDark.yellow5})`,
            focus: `light-dark(${yellow.yellow6}, ${yellowDark.yellow6})`,
            disabled: `light-dark(${yellow.yellow2}, ${yellowDark.yellow2})`,
            loading: `light-dark(${yellow.yellow3}, ${yellowDark.yellow3})`,
          },
          foreground: {
            DEFAULT: `light-dark(${yellow.yellow11}, ${yellowDark.yellow11})`,
            hover: `light-dark(${yellow.yellow12}, ${yellowDark.yellow12})`,
            active: `light-dark(${yellow.yellow12}, ${yellowDark.yellow12})`,
            focus: `light-dark(${yellow.yellow12}, ${yellowDark.yellow12})`,
            disabled: `light-dark(${yellow.yellow8}, ${yellowDark.yellow8})`,
            loading: `light-dark(${yellow.yellow9}, ${yellowDark.yellow9})`,
          },
          border: {
            DEFAULT: `light-dark(${yellow.yellow7}, ${yellowDark.yellow7})`,
            hover: `light-dark(${yellow.yellow8}, ${yellowDark.yellow8})`,
            active: `light-dark(${yellow.yellow9}, ${yellowDark.yellow9})`,
            focus: `light-dark(${yellow.yellow10}, ${yellowDark.yellow10})`,
            disabled: `light-dark(${yellow.yellow5}, ${yellowDark.yellow5})`,
            loading: `light-dark(${yellow.yellow6}, ${yellowDark.yellow6})`,
          },
        },
        info: {
          background: {
            DEFAULT: `light-dark(${blue.blue3}, ${blueDark.blue3})`,
            hover: `light-dark(${blue.blue4}, ${blueDark.blue4})`,
            active: `light-dark(${blue.blue5}, ${blueDark.blue5})`,
            focus: `light-dark(${blue.blue6}, ${blueDark.blue6})`,
            disabled: `light-dark(${blue.blue2}, ${blueDark.blue2})`,
            loading: `light-dark(${blue.blue3}, ${blueDark.blue3})`,
          },
          foreground: {
            DEFAULT: `light-dark(${blue.blue11}, ${blueDark.blue11})`,
            hover: `light-dark(${blue.blue12}, ${blueDark.blue12})`,
            active: `light-dark(${blue.blue12}, ${blueDark.blue12})`,
            focus: `light-dark(${blue.blue12}, ${blueDark.blue12})`,
            disabled: `light-dark(${blue.blue8}, ${blueDark.blue8})`,
            loading: `light-dark(${blue.blue9}, ${blueDark.blue9})`,
          },
          border: {
            DEFAULT: `light-dark(${blue.blue7}, ${blueDark.blue7})`,
            hover: `light-dark(${blue.blue8}, ${blueDark.blue8})`,
            active: `light-dark(${blue.blue9}, ${blueDark.blue9})`,
            focus: `light-dark(${blue.blue10}, ${blueDark.blue10})`,
            disabled: `light-dark(${blue.blue5}, ${blueDark.blue5})`,
            loading: `light-dark(${blue.blue6}, ${blueDark.blue6})`,
          },
        },
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    typography,
    ({ addBase, theme }: { addBase: (arg0: Record<string, Record<string, string>>) => void, theme: (arg0: string) => string }) => {
      addBase({
        ':root': {
        '--background': theme('colors.background.DEFAULT'),
        '--background-hover': theme('colors.background.hover'),
        '--background-active': theme('colors.background.active'),
        '--background-focus': theme('colors.background.focus'),
        '--background-disabled': theme('colors.background.disabled'),
        '--background-loading': theme('colors.background.loading'),
        '--foreground': theme('colors.foreground.DEFAULT'),
        '--foreground-hover': theme('colors.foreground.hover'),
        '--foreground-active': theme('colors.foreground.active'),
        '--foreground-focus': theme('colors.foreground.focus'),
        '--foreground-disabled': theme('colors.foreground.disabled'),
        '--foreground-loading': theme('colors.foreground.loading'),
        '--muted': theme('colors.muted.DEFAULT'),
        '--muted-hover': theme('colors.muted.hover'),
        '--muted-active': theme('colors.muted.active'),
        '--muted-focus': theme('colors.muted.focus'),
        '--muted-disabled': theme('colors.muted.disabled'),
        '--muted-loading': theme('colors.muted.loading'),
        '--accent': theme('colors.accent.DEFAULT'),
        '--accent-hover': theme('colors.accent.hover'),
        '--accent-active': theme('colors.accent.active'),
        '--accent-focus': theme('colors.accent.focus'),
        '--accent-disabled': theme('colors.accent.disabled'),
        '--accent-loading': theme('colors.accent.loading'),
        '--border': theme('colors.border.DEFAULT'),
        '--border-hover': theme('colors.border.hover'),
        '--border-active': theme('colors.border.active'),
        '--border-focus': theme('colors.border.focus'),
        '--border-disabled': theme('colors.border.disabled'),
        '--border-loading': theme('colors.border.loading'),
        '--ring': theme('colors.ring.DEFAULT'),
        '--ring-hover': theme('colors.ring.hover'),
        '--ring-active': theme('colors.ring.active'),
        '--ring-focus': theme('colors.ring.focus'),
        '--ring-disabled': theme('colors.ring.disabled'),
        '--ring-loading': theme('colors.ring.loading'),

        // Destructive
        '--destructive-background': theme('colors.destructive.background.DEFAULT'),
        '--destructive-background-hover': theme('colors.destructive.background.hover'),
        '--destructive-background-active': theme('colors.destructive.background.active'),
        '--destructive-background-focus': theme('colors.destructive.background.focus'),
        '--destructive-background-disabled': theme('colors.destructive.background.disabled'),
        '--destructive-background-loading': theme('colors.destructive.background.loading'),
        '--destructive-foreground': theme('colors.destructive.foreground.DEFAULT'),
        '--destructive-foreground-hover': theme('colors.destructive.foreground.hover'),
        '--destructive-foreground-active': theme('colors.destructive.foreground.active'),
        '--destructive-foreground-focus': theme('colors.destructive.foreground.focus'),
        '--destructive-foreground-disabled': theme('colors.destructive.foreground.disabled'),
        '--destructive-foreground-loading': theme('colors.destructive.foreground.loading'),
        '--destructive-border': theme('colors.destructive.border.DEFAULT'),
        '--destructive-border-hover': theme('colors.destructive.border.hover'),
        '--destructive-border-active': theme('colors.destructive.border.active'),
        '--destructive-border-focus': theme('colors.destructive.border.focus'),
        '--destructive-border-disabled': theme('colors.destructive.border.disabled'),
        '--destructive-border-loading': theme('colors.destructive.border.loading'),

        // Success
        '--success-background': theme('colors.success.background.DEFAULT'),
        '--success-background-hover': theme('colors.success.background.hover'),
        '--success-background-active': theme('colors.success.background.active'),
        '--success-background-focus': theme('colors.success.background.focus'),
        '--success-background-disabled': theme('colors.success.background.disabled'),
        '--success-background-loading': theme('colors.success.background.loading'),
        '--success-foreground': theme('colors.success.foreground.DEFAULT'),
        '--success-foreground-hover': theme('colors.success.foreground.hover'),
        '--success-foreground-active': theme('colors.success.foreground.active'),
        '--success-foreground-focus': theme('colors.success.foreground.focus'),
        '--success-foreground-disabled': theme('colors.success.foreground.disabled'),
        '--success-foreground-loading': theme('colors.success.foreground.loading'),
        '--success-border': theme('colors.success.border.DEFAULT'),
        '--success-border-hover': theme('colors.success.border.hover'),
        '--success-border-active': theme('colors.success.border.active'),
        '--success-border-focus': theme('colors.success.border.focus'),
        '--success-border-disabled': theme('colors.success.border.disabled'),
        '--success-border-loading': theme('colors.success.border.loading'),

        // Warning
        '--warning-background': theme('colors.warning.background.DEFAULT'),
        '--warning-background-hover': theme('colors.warning.background.hover'),
        '--warning-background-active': theme('colors.warning.background.active'),
        '--warning-background-focus': theme('colors.warning.background.focus'),
        '--warning-background-disabled': theme('colors.warning.background.disabled'),
        '--warning-background-loading': theme('colors.warning.background.loading'),
        '--warning-foreground': theme('colors.warning.foreground.DEFAULT'),
        '--warning-foreground-hover': theme('colors.warning.foreground.hover'),
        '--warning-foreground-active': theme('colors.warning.foreground.active'),
        '--warning-foreground-focus': theme('colors.warning.foreground.focus'),
        '--warning-foreground-disabled': theme('colors.warning.foreground.disabled'),
        '--warning-foreground-loading': theme('colors.warning.foreground.loading'),
        '--warning-border': theme('colors.warning.border.DEFAULT'),
        '--warning-border-hover': theme('colors.warning.border.hover'),
        '--warning-border-active': theme('colors.warning.border.active'),
        '--warning-border-focus': theme('colors.warning.border.focus'),
        '--warning-border-disabled': theme('colors.warning.border.disabled'),
        '--warning-border-loading': theme('colors.warning.border.loading'),

        // Info
        '--info-background': theme('colors.info.background.DEFAULT'),
        '--info-background-hover': theme('colors.info.background.hover'),
        '--info-background-active': theme('colors.info.background.active'),
        '--info-background-focus': theme('colors.info.background.focus'),
        '--info-background-disabled': theme('colors.info.background.disabled'),
        '--info-background-loading': theme('colors.info.background.loading'),
        '--info-foreground': theme('colors.info.foreground.DEFAULT'),
        '--info-foreground-hover': theme('colors.info.foreground.hover'),
        '--info-foreground-active': theme('colors.info.foreground.active'),
        '--info-foreground-focus': theme('colors.info.foreground.focus'),
        '--info-foreground-disabled': theme('colors.info.foreground.disabled'),
        '--info-foreground-loading': theme('colors.info.foreground.loading'),
        '--info-border': theme('colors.info.border.DEFAULT'),
        '--info-border-hover': theme('colors.info.border.hover'),
        '--info-border-active': theme('colors.info.border.active'),
        '--info-border-focus': theme('colors.info.border.focus'),
        '--info-border-disabled': theme('colors.info.border.disabled'),
        '--info-border-loading': theme('colors.info.border.loading'),
        },
      });
    },
  ],
};

export default config;
